### PR TITLE
Change main script entry point in package.json

### PR DESCRIPTION
**Pull request by pete-otaqui**
Specifically in my case since I was trying to load via jspm, which depends on this.

### CODE REVIEW

**Comment by Widdershin** [comment]
I am pretty sure that this change would break this package for non jspm users. Is there an alternative that would maintain compatibility?

**Comment by pete-otaqui** [comment]
Are you sure?

I think anything that is parsing the main property in the package.json,
would also expect it to point to a real file?

There is no 'lib/canvas-driver.js' (which is the value) but there is a
'src/canvas-driver.js'

Jspm does not care about the project layout, only that 'main' points to an
actual file. You could therefore rename 'src/' to 'lib/' I suppose.

Cheers,

Pete

**Comment by Widdershin** [comment]
> There is no 'lib/canvas-driver.js' (which is the value) but there is a 'src/canvas-driver.js' 

You're right, there is no 'lib/canvas-driver.js' in the repository. However, if you `npm install cycle-canvas` you'll see that there is a 'lib/canvas-driver.js'. It's the transpiled ES5 output, which is what npm users expect to be available.

So changing the main field to point at src would break this package for npm users because they can't import es6 code (even the import statement is a syntax error).

I should have explained more thoroughly at the start, my apologies.

I'm sure that there will be a way to add jspm support without totally breaking npm support. Perhaps we should both look into that?

**Comment by Widdershin** [comment]
Okay, according to the [jspm docs](https://github.com/jspm/registry/wiki/Configuring-Packages-for-jspm), we can do this:

``` js
{
  "main": "lib/canvas-driver.js",
  "jspm": {
    "main": "src/canvas-driver.js"
  }
}
```

If you update your pull request to use that approach I'd be happy to merge it.

**Comment by Widdershin** [comment]
Ooops, hadn't realized you'd made the change! Looks good 👍

**Pull request merged**
