### PR TITLE
Expose events of canvas element in sources of the driver

### PR DESCRIPTION
**Pull request by vfeskov**
should solve #16

### CODE REVIEW

**Comment by grozen** [comment]
Seriously elegant.

However, would you mind enhancing the README with information about this newfound capability?

**Comment by vfeskov** [comment]
@grozen i enhanced the readme please check

**Comment by grozen** [comment]
Awesome, thanks!

On a different matter, @Widdershin, I can't really decide what sort of version bump this merits. It is technically a breaking change as the source is now complex...

**Comment by Widdershin** [comment]
Nice contribution @vfeskov, really good start on handling events. We should next think about a way to handle detecting clicks on shapes we render on the canvas.

@grozen As far as I can see, this would be a minor version bump, since this change only adds to the public API, so users can upgrade without fear of their applications breaking.

Is there a case where an existing codebase could be broken by this change that I have missed?

**Comment by grozen** [comment]
Realistically I suppose not, seeing how there's not much to do with an empty stream.
Very well. I'll give it a small bump and a publish.

**Pull request merged**
