### PR TITLE
Add suport for rotate transformation

### PR DESCRIPTION
**Pull request by apretto**
As discussed in https://github.com/Widdershin/cycle-canvas/pull/4, a proposal for implementation of transformation in canvases.

Related to issue #2

### CODE REVIEW

**Comment by apretto** [comment]
I also have a proposal for a small refactoring for the `renderElement` function, to avoid a long list of `if`s as the number of supported elements/transformations grow: https://github.com/apretto/cycle-canvas/commit/a3aa37a2ac1a766815aec2c5ac6ed3280a7397a5

**Comment by Widdershin** [comment]
@apretto, I've merged #4 which implements translate as attributes. However, I do quite like the idea of also providing the option for using transforms as elements. Do you think you could rebuild your implementation on top of the transition as attributes work by @schempy?

**Comment by Widdershin** [comment]
@apretto could we get your nice refactor to use an object instead of ifs merged separately? It's a really nice change.

**Comment by apretto** [comment]
Closing this since the functionality was added in another PR: https://github.com/Widdershin/cycle-canvas/pull/4

**Pull request closed without merging**
