### PR TITLE
Add drawing images

### LINKED ISSUE #23: Add support for images
Often in game development you want to be able to use external images. Canvas supports drawing images, so we can as well.

### PR DESCRIPTION
**Pull request by evaogbe**
Closes #23

### CODE REVIEW

**Comment by Widdershin** [comment]
Fantastic, nice work @eoogbe!

I especially like your quality test cases.

Would you be able to add some documentation to the README for the `image` helper?

After that I'm happy to merge and publish this.

**Comment by Widdershin** [comment]
Very nice docs, thanks for adding those @eoogbe.

Happy to merge now.

**Comment by Widdershin** [comment]
Hey @schempy, could you please give me publish rights for this repo?

I think you just need to run `npm owner add widdershin cycle-canvas`.

**Comment by schempy** [comment]
@Widdershin All done! Let me know if there are any problems.

**Comment by Widdershin** [comment]
Worked a treat @schempy, thanks for that.

Released this change in v0.5.0.

@eoogbe: I've invited you to be a collaborator on this repo. This doesn't obligate you to contribute in future, but it means we can more easily collaborate as we can together on branches on this repo.

I also welcome you to review pull requests, triage issues and add more features 😄

Thanks again for contributing!

**Pull request merged**
